routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    redirect('login');
});

Route::get('/about.json', 'AboutController@generateJsonFile');

Route::auth();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');

Route::get('/office/mail', 'Office\OutlookController@mail')->name('mail');
Route::get('/office/mail/search/', 'Office\OutlookController@mailSearch')->name('mail.search');
Route::get('/office/mail/detail/{id}', 'Office\OutlookController@mailDetail')->name('mail.detail');
Route::get('/office/mail/new', 'Office\OutlookController@mailCreate')->name('mail.create');

Route::get('/office/calendar', 'Office\OutlookController@calendar')->name('calendar');
Route::get('/office/calendar/{id}', 'Office\OutlookController@calendarDetail')->name('calendar.detail');

Route::get('/office/contacts', 'Office\OutlookController@contacts')->name('contacts');

Route::get('/office/signin', 'Office\AuthController@signin');
Route::get('/office/authorize', 'Office\AuthController@getToken');

Route::get('/youtube/trends/{country}', 'Youtube\FlowController@index')->name('youtube');
Route::get('/youtube/search', 'Youtube\FlowController@search')->name('youtube.search');

resources/views/theme/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - @yield('title') </title>


    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />

</head>
<body>

  <!-- Wrapper-->
        @guest
        <div id="wrapper" class="gray-bg full-height">
            @else
        <div id="wrapper">
        @endguest

        <!-- Navigation -->
        @guest
        @else
        @include('theme.navigation')
        @endguest

        <!-- Page wraper -->
            @guest
                @else
        <div id="page-wrapper" class="gray-bg">
            @endguest

            <!-- Page wrapper -->
            @guest
            @else
            @include('theme.topnavbar')
            @endguest

            <!-- Main view  -->
            @yield('content')

            <!-- Footer -->
            @include('theme.footer')

        @guest
            @else
        </div>
            @endguest
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>

@section('scripts')
@show

</body>
</html>

resources/views/theme/footer.blade.php
<div class="footer">
    <div class="pull-right">
        Designed by Arthur GAMBLIN
    </div>
    <div>
        <strong>Dashboard</strong> Epitech &copy; 2018-2019
    </div>
</div>

resources/views/theme/navigation.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">{{ Auth::user()->name }}</strong>
                            </span> <span class="text-muted text-xs block">Dashboard<b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href={{ route('logout') }}>Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    EDB
                </div>
                <li>
                    <a href="#">
                        <i class="fa fa-th-large"></i>
                        <span class="nav-label">Office365</span>
                        <span class="fa arrow">
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse" aria-expanded="false">
                        <li class="active">
                            <a href="/office/signin">
                                <i class="fa fa-superpowers"></i>
                                <span class="nav-label">Login</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="{{ route('mail') }}">
                                <i class="fa fa-envelope-square"></i>
                                <span class="nav-label">Mail</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="{{ route('calendar') }}">
                                <i class="fa fa-calendar"></i>
                                <span class="nav-label">Calendar</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="{{ route('contacts') }}">
                                <i class="fa fa-vcard-o"></i>
                                <span class="nav-label">Contacts</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li><a href="{{ route('youtube', ["us"]) }}">
                    <i class="fa fa-caret-square-o-right"></i>
                    <span class="nav-label">YouTube</span>
                    </a>
                </li>
                <li class="{{ Request::is(['users', 'users/*']) ? 'active' : '' }}"><a href="{{ route('user.index') }}">
                    <i class="fa fa-user-o"></i>
                    <span class="nav-label">Users</span>
                    </a>
                </li>

        </ul>

    </div>
</nav>

resources/views/theme/topnavbar.blade.php
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="fa fa-sign-out"></i> Log out
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
    </nav>
</div>